site_name: Slurmy

pages:
- Slurmy:
  - Slurmy: index.md
  - HowTo: howto.md
  - Interactive Slurmy: interactive_slurmy.md
- Classes:
  - JobHandler: classes/JobHandler.md
  - JobHandlerConfig: classes/JobHandlerConfig.md
  - JobContainer: classes/JobContainer.md
  - Job: classes/Job.md
  - JobConfig: classes/JobConfig.md
  - Listener: classes/Listener.md
- Utility:
  - SuccessOutputFile: utils/SuccessOutputFile.md
  - SuccessTrigger: utils/SuccessTrigger.md
  - FinishedTrigger: utils/FinishedTrigger.md
  - LogMover: utils/LogMover.md
        
theme: rtd-dropdown
